#!/bin/sh

export EDITOR="nvim"
export BROWSER="firefox"
export XDG_CONFIG_HOME="$HOME/.config"

export USERTERM="st"
# Add scripts folder to the PATH:
if [ -d "$HOME/scripts" ]; then
  case "$HOME/scripts:" in
    $PATH) ;;
    *) if [ "${PATH##*:}"!="$HOME/scripts" ]; then
         export PATH="$PATH:$HOME/scripts"
       fi ;;
  esac
fi

# config for zsh-vim-mode
export KEYTIMEOUT=1
