#!/bin/sh

if [ -f "$SHELLCONFIG/plugins/load_plugins" ]; then
  # Plugin manager
  [ -f "$HOME/.zgenom/zgenom.zsh" ] && . "$HOME/.zgenom/zgenom.zsh"

  # Config for zsh-vim-mode
  # This needs to be loaded before the plugin in order to work
  [ -f "$SHELLCONFIG/plugins/zsh-vim-mode_config" ] && . "$SHELLCONFIG/plugins/zsh-vim-mode_config"

  if ! zgenom saved; then
  
    while read plugin; do
      zgenom load "$plugin"
    done < "$SHELLCONFIG/plugins/load_plugins"

    zgenom save

  fi
fi
