#!/bin/sh

XCONFIG_PATH=$XDG_CONFIG_HOME/x11
USERKEYBOARDSETTINGS=$XCONFIG_PATH/keyboard-settings
USERTHEME=$XCONFIG_PATH/theme
USERWALLPAPERS=$USERTHEME/wallpapers

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then xmodmap $sysmodmap
fi

# startup programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Keyboard layout
[ -f "$USERKEYBOARDSETTINGS" ] && . "$USERKEYBOARDSETTINGS"

/usr/bin/sxhkd&

# Setup theme (wallpaper and xresources)
[ -f "$USERTHEME/xresources" ] && xrdb -merge "$USERTHEME/xresources"

# Setup wallpaper
wallpaper=sky.jpg
feh --bg-scale "$USERWALLPAPERS/$wallpaper"

# Window manager. Currently using i3
session="${1:-i3}"
case "$session" in
  i3|i3wm) dbus-run-session i3          ;;
  # No known session, try to run it
  *      ) dbus-run-session "$session"  ;;
esac
