-- require("iron.core").setup({
-- 
--   config={
--     python={
--       command={"jupyter", "console", "--simple-prompt"}
--     },
--     repl_open_cmd = "botright split"
--   },
--   keymaps = {
--     send_motion = "<leader>nm", -- Send a block of code
--     visual_send = "<leader>nv", -- Send visually selected code
--     send_file = "<leader>nf",   -- Send the entire file
--     send_line = "<leader>nl",   -- Send the current line
--   },
--   highlight = {
--     italic = true, -- Highlight sent code with italics
--   },
-- })
